# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Finding inversion count by merging the left and right subset
#'
#' @param x       A vector containing real numbers with no ties
#' @param l       Index of the beginning (inclusive) of left subset
#' @param m       Index of the end (exclusive) of left subset and start (inclusive) of right subset
#' @param r       Index of the end (exclusive) of right subset
#' @return \code{inv} Inversion count
merge <- function(x, l, m, r) {
    .Call(`_kendall_merge`, x, l, m, r)
}

#' Finding inversion count of a vector using merge sort by divide-and-conquer
#'
#' @param x       A vector containing real numbers with no ties
#' @param l       Index of the beginning (inclusive) of the subset to be sorted
#' @param r       Index of the end (exclusive) of the subset to be sorted
#' @return \code{inv} Inversion count
mergeSort <- function(x, l, r) {
    .Call(`_kendall_mergeSort`, x, l, r)
}

